services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: starters-app
    ports:
      - "9090:9090"
    volumes:
      - ./:/workspace/starters/app
    environment:
      - PORT=9090
    env_file:
      - .env
    networks:
      - starters-network
    restart: always

  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    container_name: starters-ws
    ports:
      - "9091:9091"
    volumes:
      - ./websocket:/workspace/starters/websocket
    environment:
      - PORT=9091
    env_file:
      - websocket/.env
    networks:
      - starters-network
    restart: always

networks:
  starters-network:
    driver: bridge

