services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: starters-app
    ports:
      - "9090:9090"
    volumes:
      - ./:/workspace/starters/app
    environment:
      - PORT=9090
    env_file:
      - .env
    networks:
      - starters-network
    depends_on:
      - postgres
    restart: always

  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    container_name: starters-ws
    ports:
      - "9091:9091"
    volumes:
      - ./websocket:/workspace/starters/websocket
    environment:
      - PORT=9091
    env_file:
      - websocket/.env
    networks:
      - starters-network
    restart: always

  postgres:
    image: postgres:latest
    container_name: starters-db
    restart: always
    ports:
      - "9092:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ./schema/init-data.sql:/docker-entrypoint-initdb.d/02-init-data.sql
    networks:
      - starters-network

networks:
  starters-network:
    driver: bridge

volumes:
  postgres_data:

