services:
  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    container_name: starters-ws
    ports:
      - "8090:8090"
    volumes:
      - ./websocket:/workspace/starters/websocket
    env_file:
      - websocket/.env
    networks:
      - network
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8090 --reload

networks:
  network:
    driver: bridge

