

USE inventory_db;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 location VARCHAR(100) NOT NULL,
 vendor VARCHAR(100) NOT NULL,
 code VARCHAR(20) NOT NULL UNIQUE,
 price DECIMAL(10, 2) NOT NULL,
 profit DECIMAL (10, 2) NOT NULL, 
 margin INT NOT NULL,
 quantity INT NOT NULL,
 unit VARCHAR(50) NOT NULL,
 image_path VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );