name: Deploy To Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    env:
      ENVIRONMENT: staging
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      GIT_URL: ${{ secrets.GIT_URL }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      GIT_USER: ${{ secrets.GIT_USER }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Fabric and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fabric fabric2
          pip install python-decouple

      - name: Run deploy script
        run: |
          ENVIRONMENT=${{ env.ENVIRONMENT }} python3 fabfile.py

      - name: Clean up SSH Agent
        run: |
          ssh-agent -k

